server:
  port: 7002
spring:
  application:
    name: mygateway-sever
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
      - id: goods-consumer
        uri: lb://goods-consumer
        predicates:
        - Path=/detail/**,/sort/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/